### ISSUE TITLE
Error While Ordering Pixels

### ISSUE THREAD

**Issue by rorydeely** [MillionDollarScript/MillionDollarScript#25] opened 2015-04-12 13:59 UTC
I am getting the following error while ordering Pixels. I don't know why.
'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS ID, t2.field_comment AS FCOMMENT FROM form_fields AS t1, form_field_translati' at line 1'

**Comment by ty2u** [comment] 2015-04-12 16:27
Which version of MDS are you using? I think this is fixed in the development snapshot. It's caused by using the old version with MySQL 5.5.

**Comment by rorydeely** [comment] 2015-04-12 16:46
I'm using version 2.0.15. Thank you for your quick response. Could you tell me how to update it?

**Comment by ty2u** [comment] 2015-04-12 17:58
You should be able to just delete the files and upload the new ones. If you haven't done anything yet in it you should also be able to reinstall it after deleting the database tables.

**Closed** 2015-05-13 00:47 UTC
